=== RusanMaharjan/Heist-Music-Store/catalog_19031542.dtd
<!ELEMENT music-store (header,store-details,header-title,song-details+)>

<!ATTLIST music-store
  xmlns:xs CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xs:noNamespaceSchemaLocation NMTOKEN #REQUIRED>

<!ELEMENT header (header-logo,heading)>
<!ELEMENT store-details (store-name,address,telephone-number,website)>
<!ELEMENT header-title (#PCDATA)>
<!ELEMENT song-details (details,(image_1?,image_2?,image_3?,image_4?,image_5?,image_6?,image_7?,image_8?,image_9?,image_10?,
                        image_11?,image_12?,image_13?,image_14?,image_15?))>

<!ATTLIST song-details sID CDATA #REQUIRED>

<!ELEMENT header-logo EMPTY>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT store-name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone-number (#PCDATA)>
<!ELEMENT website (#PCDATA)>

<!ELEMENT details (title,description,song_name,genre,name_of_director,producer*,main_producer*,co_producer*,
                    writer*,main_writer*,co_writer*,Singer_name,Singer_age,Singer_gender,Singer_country,band*,release_year)>

<!ELEMENT image_1 EMPTY>
<!ELEMENT image_2 EMPTY>
<!ELEMENT image_3 EMPTY>
<!ELEMENT image_4 EMPTY>
<!ELEMENT image_5 EMPTY>
<!ELEMENT image_6 EMPTY>
<!ELEMENT image_7 EMPTY>
<!ELEMENT image_8 EMPTY>
<!ELEMENT image_9 EMPTY>
<!ELEMENT image_10 EMPTY>
<!ELEMENT image_11 EMPTY>
<!ELEMENT image_12 EMPTY>
<!ELEMENT image_13 EMPTY>
<!ELEMENT image_14 EMPTY>
<!ELEMENT image_15 EMPTY>

<!ELEMENT title (#PCDATA)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description desOf CDATA #REQUIRED>

<!ELEMENT song_name (#PCDATA)>
<!ATTLIST song_name sLength NMTOKEN #REQUIRED>

<!ELEMENT genre (#PCDATA)>
<!ATTLIST genre type CDATA #REQUIRED>

<!ELEMENT name_of_director (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT main_producer (#PCDATA)>
<!ELEMENT co_producer (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT main_writer (#PCDATA)>
<!ELEMENT co_writer (#PCDATA)>

<!ELEMENT Singer_name (#PCDATA)>
<!ATTLIST Singer_name singerID CDATA #REQUIRED>

<!ELEMENT Singer_age (#PCDATA)>
<!ELEMENT Singer_gender (#PCDATA)>
<!ELEMENT Singer_country (#PCDATA)>
<!ELEMENT band (#PCDATA)>
<!ELEMENT release_year (#PCDATA)>

=== RusanMaharjan/Heist-Music-Store/catalog_19031542.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Css External Link -->
<?xml-stylesheet type="text/css" href="catalog_19031542.css"?>

<!-- DTD External Link -->
<!DOCTYPE music-store SYSTEM "catalog_19031542.dtd">


<music-store xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="catalog_19031542.xsd">
   
<!-- Header -->
    <header>
        <header-logo/>
        <heading>Heist Music Store</heading>
    </header>
    

<!-- Store-details -->
    <store-details>
        <store-name>Heist Music Store</store-name>
        <address>Harisiddhi, Lalitpur</address>
        <telephone-number>01-5250417</telephone-number>        
        <website>www.HeistMusicStore.com.np</website>     
    </store-details>


<!-- header title -->
    <header-title>Songs</header-title>

<!-- Song details starts from here -->
<!-- What it feels like for a girl -->
    <song-details sID="01">
        <details>
            <title>What It Feels Like for a Girl</title>
            <description desOf="What It Feels Like for a Girl">
                <![CDATA[
                    "What It Feels Like for a Girl" is a song recorded by American Singer Madonna for her eighth studio album Music. It was released as the third and final single from the album by Maveric Records.
                ]]>
            </description>
            <song_name sLength="4:35">Name: What It Feels Like For a Girl</song_name>
            <genre type="Electronic">Genre: Pop</genre>
            <name_of_director>Director: Sigsworth</name_of_director>
            <producer>Producer: Madonna</producer>
            <writer>Writer: Madonna</writer>
            <Singer_name singerID="001">Signer Name: Madonna</Singer_name>
            <Singer_age>Singer Age: 62</Singer_age>
            <Singer_gender>Gender: Female</Singer_gender>
            <Singer_country>Country: United States</Singer_country>
            <release_year>Release Year: April 16, 2001</release_year>
        </details>
        
        <!-- Image 1 for what it feels like for a girl -->
        <image_1/>
    </song-details>

   <!-- Beliver -->
    <song-details sID="02">
        <details>
            <title>Believer</title>
            <description desOf="Believer">
                <![CDATA[
                    "Believer" is a song by American Pop Rock band Imagine Dragons. The song was released on February 1, 2017 through Interscope Records and Kidinakorner as the lead single from the band's third studio album.
                ]]>
            </description>
            <song_name sLength="3:23">Name: Believer</song_name>
            <genre type="Arena rock">Genre: Pop Rock</genre>
            <name_of_director>Director: Mattman and Robin</name_of_director>
            <main_producer>Main-Producer: Mattman</main_producer>
            <co_producer>Co-Producer: Robin</co_producer>
            <main_writer>Main-Writer: Dan Reynolds, Wayne Sermon</main_writer>
            <co_writer>Co-Writer: Ben McKee, Daniel Platzman</co_writer>
            <Singer_name singerID="002">Singer Name: Dan Reynolds</Singer_name>
            <Singer_age>Singer Age: 33</Singer_age>
            <Singer_gender>Gender: Male</Singer_gender>
            <Singer_country>Country: United States</Singer_country>
            <band>Band Name: Imagine Dragons</band>
            <release_year>Release Year: February 1, 2017</release_year>
        </details>

    <!-- Image for Believer -->
        <image_2/>
    </song-details>

    <!-- Memories -->
    <song-details sID="03">
        <details>
            <title>Memories</title>
            <description desOf="Memories">
                <![CDATA[
                    "Memories" is a song by American pop band Maroon 5, released through 222 on September 20, 2019. Lyrically, the song pays homepage to the memories of a lobed one who has since passed.
                ]]>
            </description>
            <song_name sLength="3:05">Name: Memories</song_name>
            <genre type="pop">Genre: Pop</genre>
            <name_of_director>Director: Vincent Ford</name_of_director>
            <producer>Producer: Jacod Kasher Hindlin</producer>
            <writer>Writer: Adam Levine, Stefan Johnson, Jordan Johnson</writer>
            <Singer_name singerID="003">Singer Name: Adam Levine</Singer_name>
            <Singer_age>Singer Age: 42</Singer_age>
            <Singer_gender>Gender: Male</Singer_gender>
            <Singer_country>Country: United States</Singer_country>
            <band>Band Name: Maroon 5</band>
            <release_year>Release Year: September 20, 2019</release_year>
        </details>

    <!-- Image for Memories -->
        <image_3/>
    </song-details>

    <!-- Levitating -->
    <song-details sID="04">
        <details>
            <title>Levitating</title>
            <description desOf="Levitating">
                <![CDATA[
                    "Levitating" is a song by English singer Dua Lipa from her second studio album, Future Nostalgia (2020). The song was written by Lipa, Clarence Coffee Jr., Sarah Hudson and Stephen Kozmeniuk, with the image of Mike Myers in Austin Powers in mind. 
                ]]>
            </description>
            <song_name sLength="3:41">Name: Levitating</song_name>
            <genre type="Electro-disco">Genre: pop</genre>
            <name_of_director>Director: Stephen Kozmeniuk</name_of_director>
            <producer>Producer: Stuart Price</producer>
            <writer>Writer: Clarence Coffee Jr, Sarah Hudson</writer>
            <Singer_name singerID="004">Singer Name: Dua Lipa</Singer_name>
            <Singer_age>Singer Age: 25</Singer_age>
            <Singer_gender>Gender: Female</Singer_gender>
            <Singer_country>Country: England</Singer_country>
            <release_year>Release Year: October 1, 2020</release_year>
        </details>
        
    <!-- Image for Levitating -->
        <image_4/>
    </song-details>

    <!-- Break My Heart -->
    <song-details sID="05">
        <details>
            <title>Break My Heart</title>
            <description desOf="Break My Heart">
                <![CDATA[
                    "Break My Heart" is a song by English singer Dua Lipa from her second studio album, Future Nostalgia (2020). The song was written by Lipa, Ali Tamposi, Stefan Johnson, Jordan K. Johnson, and Andrew Watt, with the latter of the five handling production alongside the Monsters & Strangerz.
                ]]>
            </description>
            <song_name sLength="3:48">Name: Break My Heart</song_name>
            <genre type="Dance-Pop">Genre: Disco</genre>
            <name_of_director>Director: Andrew Wortman</name_of_director>
            <main_producer>Main-Producer: Andrew Wortman</main_producer>
            <co_producer>Co-Producer: Andrew Watt</co_producer>
            <main_writer>Main-Writer: Stefan Johnson</main_writer>
            <co_writer>Co-Writer: Michael Hutchence</co_writer>
            <Singer_name singerID="005">Singer Name: Dua Lipa</Singer_name>
            <Singer_age>Singer Age: 25</Singer_age>
            <Singer_gender>Gender: Female</Singer_gender>
            <Singer_country>Country: England</Singer_country>
            <release_year>Release Year: March 25, 2020</release_year>
        </details>

    <!-- Image for Break My Heart -->
        <image_5/>
    </song-details>

    <!-- Friends -->
    <song-details sID="06">
        <details>
            <title>Friends</title>
            <description desOf="Friends">
                <![CDATA[
                    "Friends" (stylized in all caps) is a song by American record producer Marshmello and English singer Anne-Marie. It was written and produced by Marshmello, with additional writing from Anne-Marie, Eden Anderson, Richard Boardman, Jasmine Thompson, Nat Dunn, Sarah Blanchard and Pablo Bowman.
                ]]>
            </description>
            <song_name sLength="3:26">Name: Friends</song_name>
            <genre type="EDM">Genre: Pop</genre>
            <name_of_director>Director: Marshmello</name_of_director>
            <producer>Producer: Marshmello</producer>
            <writer>Writer: Eden Andreson, Natalie Dunn</writer>
            <Singer_name singerID="006">Singer Name: Anne Marie</Singer_name>
            <Singer_age>Singer Age: 30</Singer_age>
            <Singer_gender>Gender: Female</Singer_gender>
            <Singer_country>Country: England</Singer_country>
            <release_year>Release Year: February 9, 2018</release_year>
        </details>

    <!-- Image for Friends -->
        <image_6/>
    </song-details>

    <!-- At my worst -->
    <song-details sID="07">
        <details>
            <title>At My Worst</title>
            <description desOf="At My Worst">
                <![CDATA[
                    Pink Sweat’s “At My Worst” is one of his latest hits, and it’s already racked up more than 34 million Spotify plays to date. The song, which is produced by John Hill and Pink Sweat$, appears on his 2020 EP, The Prelude. On the track, the Philly native sings about finding a partner who will stick with him despite his flaws.
                ]]>
            </description>
            <song_name sLength="3:12">Name: At my worst</song_name>
            <genre type="pop">Genre: soul pop</genre>
            <name_of_director>Director: David Bowden</name_of_director>
            <producer>Producer: David Bowden</producer>
            <writer>Writer: David Bowden</writer>
            <Singer_name singerID="007">Singer Name: David Bowden</Singer_name>
            <Singer_age>Singer Age: 29</Singer_age>
            <Singer_gender>Gender: Male</Singer_gender>
            <Singer_country>Country: United States</Singer_country>
            <band>Band Name: Pink Sweat's</band>
            <release_year>Release Year: November 12, 2020</release_year>
        </details>

    <!-- Image for At my worst -->
        <image_7/>
    </song-details>

    <!-- I'm a Mess -->
